src/account/urls.py
from django.urls import path

from account.views import UserLogin, UserLogout, UserRegistration

app_name = "account"

urlpatterns = [
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", UserLogout.as_view(), name="logout"),
    path("registration/", UserRegistration.as_view(), name="registration"),
]

src/api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import CustomerViewSet, QuestionDetailView, QuizListView

app_name = "api"
router = routers.DefaultRouter()
router.register("customers", CustomerViewSet)

urlpatterns = [
    path("", include(router.urls)),
    path("quiz/<int:pk>/question/<int:order_number>/", QuestionDetailView.as_view(), name="question_details"),
    path("quiz/", QuizListView.as_view(), name="quiz_list"),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("api/", include("api.urls")),
    path("", include("quiz.urls")),
    path("account/", include("account.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/quiz/urls.py
from django.urls import path

from quiz.views import (CategoryDetailView, IndexView, QuizDetailView,
                        ResultView, SubmitQuizView)

app_name = "quiz"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="categories"),
    path("quiz/<int:pk>/", QuizDetailView.as_view(), name="quiz"),
    path("submit/<int:quiz_pk>/", SubmitQuizView.as_view(), name="submit"),
    path("result/<int:quiz_pk>/", ResultView.as_view(), name="result"),
]

src/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Quiz App</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'img/f_icon.png' %}">
</head>

<body>
<header class="bg-blue-300 text-white py-4">
    <nav class="container mx-auto px-4 flex flex-col md:flex-row justify-between items-center">
        <h1 class="text-2xl font-bold">Quiz App</h1>
        <ul class="flex space-x-4 mt-4 md:mt-0 mx-4">
            <li><a href="{% url 'quiz:index' %}" class="text-blue-800 hover:text-white">Home</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'account:logout' %}" class="text-blue-800 hover:text-white">Logout</a></li>
            {% else %}
                <li><a href="{% url 'account:login' %}" class="text-blue-800 hover:text-white">Login</a></li>
                <li><a href="{% url 'account:registration' %}" class="text-blue-800 hover:text-white">Sign In</a></li>
            {% endif %}
        </ul>
    </nav>
</header>
{% block content %}
    <main class="container mx-auto py-8 flex justify-center">
    <div class="bg-white rounded-lg shadow-lg p-8 text-center">
        <h2 class="text-3xl font-bold mb-6">Check your programming learning with next quizzes</h2>
        <h2 class="text-2xl font-bold mb-4">Quizzes:</h2>
        <ul class="space-y-4">
            {% for category in categories %}
                <li class="flex flex-col items-center border-2 border-gray-300 rounded-lg p-4">
                    <p>{{ category.name }}</p>
                    {% if category.image %}
                        <img src="{{ category.image.url }}" alt="Category Image" width="200px" height="200px" class="mx-auto">
                    {% else %}
                        <img src="{% static 'img/quiz.jpg' %}" alt="Category Image" width="200px" height="200px" class="mx-auto">
                    {% endif %}
                    <p>{{ category.description }}</p>
                    <br>
                    <a href="{% url 'quiz:categories' pk=category.pk %}" class="text-blue-800">Choose quizzes in {{ category.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</main>
{% endblock %}
</body>
</html>